### ISSUE TITLE
AttributeError: module 'config' has no attribute 'logs'

### ISSUE THREAD

**Issue by Zerbaib** [Person0z/discord.py-template#25]
```Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/disnake/client.py", line 700, in _run_event
    await coro(*args, **kwargs)
  File "/home/huggg/BotDiscordPy/cogs/logging.py", line 26, in on_message_delete
    if message.channel.id in config.logs:
AttributeError: module 'config' has no attribute 'logs'
```

**Comment by Zerbaib** [comment]
i think in ``config.py`` the lasted ligne ``35`` you need to change

``deleted_logs`` into ``logs``

**Comment by Person0z** [comment]
Fixed
